### ISSUE TITLE
any possible way to allow injecting a header

### ISSUE THREAD

**Issue by sgraham785** [smartystreets/scanners#3]
I have a client that sends a large file without headers. We have an agreed upon header map, so the file is consistent, they just choose to not send the headers in the file. I would like to inject the headers from a config without having to read the file first in another process. 

The easiest way would be to append the headers in *ColumnScanner.headerRecord []string, but since it's an unexported field I cannot do that. 

Any thought into making that field exported or adding this functionality in a func?

**Comment by mdwhatcott** [comment]
Ah, I see. I'll review your PR and get back to you in the next few days. Stay tuned...

**Comment by mdwhatcott** [comment]
I should mention that I rarely use the ColumnScanner and the StructScanner. They were fun to build, but are narrowly focused. Generally, I embed the simple csv.Scanner on my own custom scanner on a per-schema basis. Something like this:

```
type CustomRecord struct {
	Field1 string
	Field2 string
	Field3 string
}

type CustomScanner struct{ *csv.Scanner }

func NewCustomScanner(reader io.Reader) *CustomScanner {
	return &CustomScanner{csv.NewScanner(reader, csv.Comma('\t'))}
}

// override the Record() method to provide my the custom record instead of []string:
func (this *Scanner) Record() CustomRecord {
	record := this.Scanner.Record()
	return CustomRecord{
		Field1: record[0],
		Field2: record[1],
		Field3: record[2],
	}
}
```
